### ISSUE TITLE
`py.test` is no longer available

### ISSUE THREAD

**Issue by frenzymadness** [degauden/Elements#17]
pytest 7.2.0 no longer depends on `py` module which means that the import of `py.test` will no longer work.

https://github.com/degauden/Elements/blob/c79a755150beaba70b42fc11ecc9245dc614683a/ElementsServices/tests/python/DataSynchronizer_test.py#L21

**Comment by degauden** [comment]
Indeed. A bit of a surprise.

Many thanks for the report. I'll fix this ASAP.

**Comment by degauden** [comment]
Fixed in f339c678fbcadbcc011e099a620725d47dc105ff
