### ISSUE TITLE
make rpm failure

### ISSUE THREAD

**Issue by ebertin** [degauden/Elements#2]
Elements compiles and installs fine on my Fedora 28 system (after having installed all the depencies, eg., `cfitsio-devel`, etc.). However `make rpm` returns the following error message:

```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/bertin/sources/Elements/build/Packages/RPM/BUILDROOT/Elements-5.5-1.fc28.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/bin/CfitsioExample
   /usr/lib/debug/usr/bin/CfitsioExample-5.5-1.fc28.x86_64.debug

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/bin/CfitsioExample
   /usr/lib/debug/usr/bin/CfitsioExample-5.5-1.fc28.x86_64.debug
make[3]: *** [CMakeFiles/rpm.dir/build.make:58: CMakeFiles/rpm] Error 1
make[2]: *** [CMakeFiles/Makefile2:1092: CMakeFiles/rpm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1099: CMakeFiles/rpm.dir/rule] Error 2
make: *** [Makefile:613: rpm] Error 2

```
Also, how can I do to avoid ending up with all those test executables in `/usr/bin`?

**Comment by degauden** [comment]
I think I understand the issue: some Elements modules were located during the configure step from within the "build" directory and thus failed the build. The fix in 6312ba1f3a6b371f9c0fad4e3aca62dcf050de81 should cure that.

**Comment by degauden** [comment]
For the second question: for the moment, there is no way to distinguish (rpm-wise) the regular executables from the test ones. In the future, I plan to have a dedicated Elements-tests-5.5-1.fc29.x86_64.rpm file to ship them separately. From the same move, I would disable their installation (but not their build) with a CMake option.

**Comment by ebertin** [comment]
You nailed it! Thanks.
